### ISSUE TITLE
Containerization for ease of use

### ISSUE THREAD

**Issue by amuhammadctac** [lirantal/is-website-vulnerable#52]
**Is your feature request related to a problem? Please describe.**
It's not directly related to a problem, but I think that providing a Dockerfile for either building and running the container by themselves, or a docker image would be useful.

**Describe the solution you'd like**
I have already dockerized it's usage without having to install all the pre-requisites by the end users. I would like to request being added as contributor so that I can push a feature branch and create a pull request for master branch. Ofcourse, the choice to approve or deny the Pull Request is all yours 😄 

**Describe alternatives you've considered**
1. Shell Scripts
2. Ansible

P.S Nothing else feels more isolated and easy to use than docker for is-website-vulnerable as it doesn't require being up all the time.

**Comment by lirantal** [comment]
@amuhammadctac hey, that's actually pretty cool.
would you be happy to contribute that Dockerfile here? I'm happy to add you as an author if we can publish the image and consume it under something like `https://hub.docker.com/r/lirantal/is-website-vulnerable` so we can communicate proper origin/source trust

**Comment by darkwizard242** [comment]
@lirantal  - Apologies, actually the user @amuhammadctac is my work GitHub account and I ended up creating this Issue 52 using @amuhammadctac  by mistake instead of my personal one. Which is why I created a duplicate issue [53](https://github.com/lirantal/is-website-vulnerable/issues/53) using my personal GitHub account.

Yup, I am more than happy to contribute the Dockerfile as a PR to the repository [is-website-vulnerable](https://github.com/lirantal/is-website-vulnerable). If you could please add my user @darkwizard242 as a contributor, I can push my local feature branch to the repository and create a PR to master branch for you to review and accept. I may also add a section around how to utilize the docker containers for the ease of end users. 

As for the docker image on DockerHub, I am assuming you would prefer that under your ownership within [your](https://hub.docker.com/u/lirantal) DockerHub account. Once the branch/Dockerfile is merged, you will just need to build and push to DockerHub or utilize automated builds feature in Dockerhub to do that for you 👍

**Comment by lirantal** [comment]
@darkwizard242 sounds good indeed to add both the Dockerfile as well as updating the README to explain how to use it. You should be able to simply fork the repository and push a Pull Request to do so.

Sounds good about DockerHub 👍

Let me know if there's anything I can help with.

**Comment by darkwizard242** [comment]
@lirantal  - Thank you. I have created a [PR](https://github.com/lirantal/is-website-vulnerable/pull/57) for the change.

I have added a section in README for local build/run of Docker image/container. However, that will need to be updated once you have created a repository on DockerHub under your account to build and host the Docker image tags for anyone to pull down 👍

**Comment by lirantal** [comment]
Looks good, let's continue the conversation on the PR

**Comment by darkwizard242** [comment]
Sure @lirantal  - Good with me. Please tag me to the PR with any comments (for visibility so I don't lose track :) )
